[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[headers]]
  for = "/*"
[headers.values]
  X-Frame-Options = "ALLOW-FROM https://nhexa.cl https://laruina.cl https://terminalcore.cl"
  Content-Security-Policy = "frame-ancestors 'self' https://nhexa.cl https://laruina.cl https://terminalcore.cl"
